name: 📦 Build & Publish

# Trigger on push to main, or on new GitHub release
on:
  push:
    branches:
      - main
  # optionally, only when you create a Git tag or GitHub release:
  # release:
  #   types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.17.0]
    steps:

      # 1. Check out your code
      - uses: actions/checkout@v4

      # 2. Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Install dependencies & compile TypeScript
      - run: npm install
      - run: npm run compile

      # 4. Install vsce locally and publish
      - name: Install vsce locally
        run: |
          npm install @vscode/vsce@latest
        
      # 5. Verify Node.js and vsce versions
      - name: Verify versions
        run: |
          node --version
          npm --version
          npx vsce --version
        
      # 6. Publish to the Marketplace
      - name: Publish Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish
